[package]
name = "libtag_aggregator"
version = "0.1.0"
edition = "2018"

[dependencies]

# JSON serialization
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"

# IPC
dbus = "0.6.5"
glib = "0.8.0"
