[package]
name = "tag-aggregator-server"
version = "0.1.0"
edition = "2018"

[dependencies]
libtag_aggregator = { path = "../libtag-aggregator" }
# HTTP
rouille = "3.0.0"
# JSON serialization
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"